apiVersion: apps/v1
kind: Deployment
metadata:
  name: instant-bible-api
  namespace: instant-bible
spec:
  selector:
    matchLabels:
      app: instant-bible-api
  template:
    metadata:
      labels:
        app: instant-bible-api
    spec:
      containers:
        - name: instant-bible-api
          image: #IMAGE
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 500m
      imagePullSecrets:
        - name: gh-container-registry
