[package]
name = "engine-proto"
version = "0.0.0"
authors = ["Kenneth Powers <ken@kenpowers.net>"]
edition = "2018"

[dependencies]
anyhow = "1.0.26"
prost = "0.6.1"
serde = { version = "1.0.104", features = ["derive"] }

[build-dependencies]
prost-build = "0.6.1"
