[package]
name = "server"
version = "0.0.0"
publish = false
authors = ["Kenneth Powers <ken@kenpowers.net> (https://knpw.rs)"]
edition = "2018"

[dependencies]
actix-protobuf = "0.4.1"
actix-web = "1.0.8"
engine = { path = "../engine" }
env_logger = "0.7.0"
log = "0.4.8"
serde = "1.0.101"
