[package]
name = "engine"
version = "0.0.0"
publish = false
authors = ["Kenneth Powers <ken@kenpowers.net> (https://knpw.rs)"]
edition = "2018"

[dependencies]
anyhow = "1.0.26"
criterion = "0.3.0"
engine-proto = { path = "../engine-proto" }
env_logger = "0.7.1"
envy = "0.4.1"
fst = "0.3.5"
fst-levenshtein = "0.2.1"
itertools = "0.8.2"
log = "0.4.8"
serde = { version = "1.0.104", features = ["derive"] }

[[bench]]
name = "search"
harness = false

[[bench]]
name = "tokenize"
harness = false
