[package]
name = "engine"
version = "0.0.0"
publish = false
authors = ["Kenneth Powers <ken@kenpowers.net> (https://knpw.rs)"]
edition = "2018"

[dependencies]
anyhow = "1.0.26"
bytes = "0.5.4"
criterion = "0.3.0"
env_logger = "0.7.1"
envy = "0.4.1"
fst = { version = "0.4.0", features = ["levenshtein"] }
itertools = "0.8.2"
lazy_static = "1.4.0"
log = "0.4.8"
prost = "0.6.1"
regex = "1.3.4"
serde = { version = "1.0.104", features = ["derive"] }
wasm-timer = "0.2.5"

[build-dependencies]
prost-build = "0.6.1"

[[bench]]
name = "search"
harness = false

[[bench]]
name = "tokenize"
harness = false
