[package]
name = "bgram"
version = "0.0.0"
publish = false
authors = ["Kenneth Powers <ken@kenpowers.net> (https://knpw.rs)"]
edition = "2018"

[dependencies]
actix-web = "1.0.8"
env_logger = "0.7.0"
envy = "0.4.0"
itertools = "0.8.0"
log = "0.4.8"
serde = { version = "1.0.101", features = ["rc"] }
serde_json = "1.0.41"
regex = "1.3.1"
bincode = "1.2.0"
lazy_static = "1.4.0"
