name: Build and Deploy Website

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build-and-deploy-website.yml
      - packages/bridge-wasm/**
      - packages/engine/**
      - packages/proto/**
      - packages/web/**

jobs:
  build-and-deploy-website:
    runs-on: ubuntu-latest
    steps:
      - uses: jetli/wasm-pack-action@v0.3.0
      - uses: actions/checkout@v2
      - name: Install Dependencies
        working-directory: packages/web
        run: npm ci
      - name: Prepare
        id: prep
        run: |
          SENTRY_RELEASE="instantbible-web@$(echo $GITHUB_SHA | head -c7)"
          echo ::set-output name=sentry_release::$SENTRY_RELEASE
      - name: Build
        working-directory: packages/web
        env:
          SENTRY_RELEASE: ${{ steps.prep.outputs.sentry_release }}
        run: npm run build
      - name: Create Sentry Release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT_WEB }}
        with:
          environment: production
          sourcemaps: packages/web/dist
          version: ${{ steps.prep.outputs.sentry_release }}
      - name: Deploy
        working-directory: packages/web
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: npm run deploy -- --message $(echo $GITHUB_SHA | head -c7)
