name: CI (Rust)

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/ci-rust.yml
      - packages/bridge-c/**
      - packages/bridge-wasm/**
      - packages/engine/**
      - packages/proto/**
      - packages/server/**
  pull_request:
    paths:
      - .github/workflows/ci-rust.yml
      - packages/bridge-c/**
      - packages/bridge-wasm/**
      - packages/engine/**
      - packages/proto/**
      - packages/server/**

jobs:
  build-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: allenevans/set-env@v1.0.0
        with:
          SERVER_SENTRY_DSN: https://9965738e8eac44b9922b71951141f59d@o387306.ingest.sentry.io/5222373
      - name: Build
        working-directory: packages
        run: cargo build --verbose
      - name: Test
        working-directory: packages
        run: cargo test --verbose
      - name: Clippy
        working-directory: packages
        run: cargo clippy
