name: CI (Web)

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/ci-web.yml
      - packages/bridge-wasm/**
      - packages/engine/**
      - packages/proto/**
      - packages/web/**

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: jetli/wasm-pack-action@v0.3.0
      - uses: actions/checkout@v1
      - name: Install
        working-directory: packages/web
        run: npm ci
      - name: Build
        working-directory: packages/web
        run: npm run build
      - name: Check
        working-directory: packages/web
        run: npm run check
